export const emailsData = [
  {
    id: 0,
    name: 'Mark',
    title: 'Hello, man',
    message: 'This is your first message',
    date: '27.05.19',
    favorite: false,
    unread: true,
    attachment: true,
  },
  {
    id: 1,
    name: 'Tony',
    title: 'Hey, I just wanna talk with you',
    message: 'This is your first message',
    date: '27.05.19',
    favorite: false,
    unread: true,
    attachment: false,
  },
  {
    id: 2,
    name: 'Widow',
    title: 'empty title',
    message: 'This is your first message',
    date: '27.05.19',
    favorite: true,
    unread: false,
    attachment: true,
  },
  {
    id: 3,
    name: 'Mark',
    title: 'Hello, dude',
    message: 'This is your first message',
    date: '27.05.19',
    favorite: false,
    unread: true,
    attachment: true,
  },
  {
    id: 4,
    name: 'Tony',
    title: 'Hey, I just wanna talk with you',
    message: 'This is your first message',
    date: '27.05.19',
    favorite: false,
    unread: true,
    attachment: false,
  },
  {
    id: 5,
    name: 'Widow',
    title: 'empty title',
    message: '2This is your first message',
    date: '27.05.19',
    favorite: true,
    unread: false,
    attachment: true,
  },
  {
    id: 6,
    name: 'Mark',
    title: 'Hello, dude',
    message: 'This is your first message',
    date: '27.05.19',
    favorite: false,
    unread: true,
    attachment: true,
  },
  {
    id: 7,
    name: 'Tony',
    title: 'Hey, I just wanna talk with you',
    message: 'This is your first message',
    date: '27.05.19',
    favorite: false,
    unread: true,
    attachment: false,
  },
  {
    id: 8,
    name: 'Widow',
    title: 'empty title',
    message: '2This is your first message',
    date: '27.05.19',
    favorite: true,
    unread: false,
    attachment: true,
  },
  {
    id: 9,
    name: 'Mark',
    title: 'Hello, dude',
    message: 'This is your first message',
    date: '27.05.19',
    favorite: false,
    unread: true,
    attachment: true,
  },
  {
    id: 10,
    name: 'Tony',
    title: 'Hey, I just wanna talk with you',
    message: 'This is your first message',
    date: '27.05.19',
    favorite: false,
    unread: true,
    attachment: false,
  },
  {
    id: 11,
    name: 'Widow',
    title: 'empty title',
    message: '2This is your first message',
    date: '27.05.19',
    favorite: true,
    unread: false,
    attachment: true,
  },
  {
    id: 12,
    name: 'Mark',
    title: 'Hello, dude',
    message: 'This is your first message',
    date: '27.05.19',
    favorite: false,
    unread: true,
    attachment: true,
  },
  {
    id: 13,
    name: 'Tony',
    title: 'Hey, I just wanna talk with you',
    message: 'This is your first message',
    date: '27.05.19',
    favorite: false,
    unread: true,
    attachment: false,
  },
  {
    id: 14,
    name: 'Widow',
    title: 'empty title',
    message: '2This is your first message',
    date: '27.05.19',
    favorite: true,
    unread: false,
    attachment: true,
  },
  {
    id: 15,
    name: 'Mark',
    title: 'Hello, dude',
    message: 'This is your first message',
    date: '27.05.19',
    favorite: false,
    unread: true,
    attachment: true,
  },
  {
    id: 16,
    name: 'Tony',
    title: 'Hey, I just wanna talk with you',
    message: 'This is your first message',
    date: '27.05.19',
    favorite: false,
    unread: true,
    attachment: false,
  },
  {
    id: 17,
    name: 'Widow',
    title: 'empty title',
    message: '2This is your first message',
    date: '27.05.19',
    favorite: true,
    unread: false,
    attachment: true,
  },
];
